--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deno-rest-api-deployment
  labels:
    app: deno
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: deno
  template: 
    metadata: 
      labels: 
        app: deno
    spec: 
      containers: 
        - 
          image: "nginx:1.7.9"
          name: deno
          ports: 
            - 
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: deno-rest-api-entrypoint
  type: NodePort
  selector:
    app: deno
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001